/**
 * Portfolio collections (FR-02, FR-03).
 *
 * `cover` and `images` reference filenames in photos/raw/ without extension.
 * To publish a new wedding: drop photos into photos/raw/, add an entry here,
 * run `npm run build`. No markup changes required (US-5).
 *
 * NOTE: all imagery here is Unsplash-licensed placeholder work — see
 * photos/CREDITS.md — and the couples are invented. Replace both before launch.
 */
export default [
  {
    slug: 'ramparts-at-six',
    title: 'The Ramparts at Six',
    couple: 'Amara & Rohan',
    placeholder: true,
    venue: 'Galle Fort, and a courtyard behind it',
    location: 'Galle',
    season: 'February',
    guests: 68,
    cover: 'coastal-03',
    featured: true,
    excerpt:
      'Everyone wants the fort walls at six. We got there at half five and shared them with two other weddings.',
    story: [
      'They wanted the ramparts at six, which is the right answer and also the answer every photographer in this country will give you.',
      'The trouble with Galle in February is that everybody else wants it too. We were up on the wall by half five and shared it with two other weddings and roughly sixty tourists waiting for the same sunset. Amara did not care even slightly. She had been up since four getting her hair done and said the wind was the first thing all day that had felt good.',
      'Most of what I actually like from this wedding happened later, after the light had gone and people had stopped arranging themselves. There is a photograph in here of Rohan’s father asleep in a plastic chair at eleven at night, still holding a plate. That one is my favourite.',
    ],
    images: [
      'coastal-03',
      'coastal-01',
      'coastal-07',
      'coastal-02',
      'coastal-09',
      'coastal-04',
      'detail-01',
      'coastal-05',
      'portrait-02',
      'coastal-08',
      'coastal-06',
      'detail-05',
      'coastal-10',
      'coastal-11',
      'coastal-12',
      'portrait-06',
    ],
  },
  {
    slug: 'long-table-low-light',
    title: 'Long Table, Low Light',
    couple: 'Priya & Tom',
    placeholder: true,
    venue: 'The veranda of a tea bungalow',
    location: 'Dickoya, hill country',
    season: 'March',
    guests: 120,
    cover: 'barn-02',
    featured: true,
    excerpt:
      'One table. A hundred and twenty people. Her mother thought it was a terrible idea for four months.',
    story: [
      'Priya wanted one table. Not a top table. One table, a hundred and twenty people, running end to end down the veranda of a tea bungalow outside Dickoya.',
      'Her mother thought this was a disaster waiting to happen, held that position for about four months, and then changed her mind somewhere around nine o’clock on the night. I have that on record, because I photographed her saying so.',
      'What nobody planned for was the cold. It drops hard up there once the sun goes, and half the guests in these photographs are wearing somebody else’s shawl. The speeches ran forty minutes over. Not one person got up to leave.',
      'If you hate having your photograph taken, this is the gallery I would send you. Hardly anyone in it is looking at me.',
    ],
    images: [
      'barn-02',
      'barn-01',
      'detail-02',
      'barn-04',
      'barn-03',
      'barn-05',
      'detail-06',
      'barn-06',
      'portrait-03',
      'barn-07',
      'barn-08',
      'detail-03',
      'barn-09',
      'barn-10',
      'detail-08',
      'portrait-05',
    ],
  },
  {
    slug: 'two-witnesses',
    title: 'Two Witnesses and a Mountain',
    couple: 'Elena & Jonah',
    placeholder: true,
    venue: 'A ridge above Ella, reached on foot',
    location: 'Ella',
    season: 'August',
    guests: 4,
    cover: 'elope-02',
    featured: true,
    excerpt: 'The ceremony lasted eleven minutes. That is shorter than the drive to the trailhead.',
    story: [
      'They emailed in March to ask whether I would be willing to walk up a mountain carrying my own kit. I said yes before I properly looked at the route, which is a habit I should probably break.',
      'We left Ella at four in the morning in the dark. The ceremony was at sunrise and it lasted eleven minutes, which is shorter than the drive to the trailhead. Four people were there, and one of them was me.',
      'An elopement is not a small wedding. It is a different job entirely. You stop directing, you start keeping up, and you carry your own water.',
    ],
    images: [
      'elope-02',
      'elope-01',
      'elope-03',
      'elope-05',
      'portrait-01',
      'elope-04',
      'elope-06',
      'detail-07',
      'elope-07',
      'elope-08',
      'portrait-04',
      'detail-04',
    ],
  },
];
