#!/usr/bin/env node
/**
 * Downloads webfonts from Google Fonts and self-hosts them under
 * src/assets/fonts/, then writes src/styles/fonts.css with matching @font-face
 * rules pointing at the local copies.
 *
 * Self-hosting is a hard requirement (NFR-07): the production site must make
 * zero third-party requests. This script runs at author time, not build time.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'src', 'assets', 'fonts');
const CSS_OUT = join(ROOT, 'src', 'styles', 'fonts.css');
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const SPEC =
  'family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400' +
  '&family=Jost:wght@300;400;500&display=swap';

/** Split Google's CSS into {subset, family, style, weight, url, range} records. */
function parse(css) {
  const faces = [];
  // Each face is preceded by a `/* subset */` comment.
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i];
    const body = parts[i + 1] ?? '';
    const pick = (re, fallback = '') => (body.match(re) ?? [, fallback])[1];
    const url = pick(/(https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)/, '');
    if (!url) continue;
    faces.push({
      subset,
      family: pick(/font-family:\s*['"]([^'"]+)/),
      style: pick(/font-style:\s*(\w+)/, 'normal'),
      weight: pick(/font-weight:\s*(\d+)/, '400'),
      range: pick(/unicode-range:\s*([^;]+)/),
      url,
    });
  }
  return faces;
}

const slugify = (f) =>
  `${f.family.toLowerCase().replace(/\s+/g, '-')}-${f.weight}` +
  `${f.style === 'italic' ? '-italic' : ''}-${f.subset}`;

await mkdir(FONT_DIR, { recursive: true });

const res = await fetch(`https://fonts.googleapis.com/css2?${SPEC}`, {
  headers: { 'User-Agent': UA },
});
if (!res.ok) throw new Error(`Google Fonts CSS: HTTP ${res.status}`);

const faces = parse(await res.text()).filter((f) => KEEP_SUBSETS.has(f.subset));
console.log(`Self-hosting ${faces.length} font files → src/assets/fonts/`);

let bytes = 0;
for (const f of faces) {
  const name = `${slugify(f)}.woff2`;
  const buf = Buffer.from(
    await fetch(f.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
  );
  await writeFile(join(FONT_DIR, name), buf);
  f.file = name;
  bytes += buf.length;
}

const css = [
  '/* GENERATED by tools/fetch-fonts.mjs — do not edit by hand. */',
  '/* Cormorant Garamond & Jost are licensed under the SIL Open Font License 1.1. */',
  '',
  ...faces.map((f) =>
    [
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      '  font-display: swap;',
      `  src: url('/assets/fonts/${f.file}') format('woff2');`,
      `  unicode-range: ${f.range};`,
      '}',
    ].join('\n'),
  ),
  '',
].join('\n');

await writeFile(CSS_OUT, css);
console.log(`  ${(bytes / 1024).toFixed(0)} KB total; wrote src/styles/fonts.css`);
